import sys
import random
from PyQt6 import QtWidgets
def countAttemps():
    broski = int(input_text.text())
    arr_results = []
    for x in range(broski):
        arr_results.append(random.randint(1, 6))
    res_1 = str(round(arr_results.count(1) / broski * 100, 2))
    res_2 = str(round(arr_results.count(2) / broski * 100, 2))
    res_3 = str(round(arr_results.count(3) / broski * 100, 2))
    res_4 = str(round(arr_results.count(4) / broski * 100, 2))
    res_5 = str(round(arr_results.count(5) / broski * 100, 2))
    res_6 = str(round(arr_results.count(6) / broski * 100, 2))
    result.setText("<b>Вероятность выпадения 1 очка:</b> "+res_1+"<br><b>Вероятность выпадения 2 очка:</b> "+res_2+"<br><b>Вероятность выпадения 3 очка:</b> "+res_3+"<br><b>Вероятность выпадения 4 очка:</b> "+res_4+"<br><b>Вероятность выпадения 5 очка:</b> "+res_5+"<br><b>Вероятность выпадения 6 очка:</b> "+res_6)
    label.hide()
    input_text.hide()
    btnSend.hide()
    btnQuit.show()
    input_text.setText("")
    result.show()
app = QtWidgets.QApplication(sys.argv)
window = QtWidgets.QWidget()
window.setWindowTitle("Статистика")
window.resize(300, 70)
label = QtWidgets.QLabel("<center>Сколько бросков надо произвести?</center>")
input_text = QtWidgets.QLineEdit()
btnSend = QtWidgets.QPushButton("Вычислить")
btnQuit = QtWidgets.QPushButton("Закрыть")
result = QtWidgets.QLabel("")
vbox = QtWidgets.QVBoxLayout()
vbox.addWidget(label)
vbox.addWidget(input_text)
vbox.addWidget(btnSend)
vbox.addWidget(result)
vbox.addWidget(btnQuit)
result.hide()
btnQuit.hide()
window.setLayout(vbox)
btnSend.clicked.connect(countAttemps)
btnQuit.clicked.connect(app.quit)
window.show()
sys.exit(app.exec())
